{
 "title": "NTULab Material Stocks for LD",
 "description": "Stock list for all LD materials",
 "time": { "from": "2026-01-10T17:37:48.095Z", "to": "2026-01-11T17:37:48.095Z" },
 "panels": [
  {
   "title": "LD Full",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Baseplate",
     "type": "stat",
     "description": "Count of free baseplates",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "hgcdb",
       "rawSql": "SELECT COUNT(bp.bp_name)\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Full'\n  AND pr.proto_name is NULL"
      }
     ]
    },
    {
     "title": "Sensor",
     "type": "stat",
     "description": "Count of free sensors",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "hgcdb",
       "rawSql": "SELECT COUNT(material.sen_name)\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Full'\n  AND pmodule.proto_name is NULL\n"
      }
     ]
    },
    {
     "title": "hexaboard",
     "type": "stat",
     "description": "Count of free hexaboard\nCheck free entry in **hexaboard** and they are not recorded in **module_assembly** table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "hgcdb",
       "rawSql": "SELECT COUNT(material.hxb_name)\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Full'\n  AND module.module_name is NULL"
      }
     ]
    },
    {
     "title": "ID",
     "type": "table",
     "description": "names of baseplates",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "dataset": "hgcdb",
       "rawSql": "SELECT bp.bp_name\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Full'\n  AND pr.proto_name is NULL\nORDER BY bp_name ASC;"
      }
     ]
    },
    {
     "title": "ID",
     "type": "table",
     "description": "names of baseplates",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "dataset": "hgcdb",
       "rawSql": "SELECT material.sen_name\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Full'\n  AND pmodule.proto_name is NULL\nORDER BY material.sen_name ASC"
      }
     ]
    },
    {
     "title": "ID",
     "type": "table",
     "description": "names of hexaboard",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 9 },
     "targets": [
      {
       "dataset": "hgcdb",
       "rawSql": "SELECT material.hxb_name\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Full'\n  AND module.module_name is NULL\nORDER BY material.hxb_name ASC \n"
      }
     ]
    }
   ]
  },
  { "title": "LD Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Baseplate",
   "type": "stat",
   "description": "Count of free baseplates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(bp.bp_name)\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Top'\n  AND pr.proto_name is NULL"
    }
   ]
  },
  {
   "title": "Sensor",
   "type": "stat",
   "description": "Count of free sensors",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.sen_name)\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Top'\n  AND pmodule.proto_name is NULL\n"
    }
   ]
  },
  {
   "title": "hexaboard",
   "type": "stat",
   "description": "Count of free hexaboard\nCheck free entry in **hexaboard** and they are not recorded in **module_assembly** table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.hxb_name)\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Top'\n  AND module.module_name is NULL"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT bp.bp_name\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Top'\n  AND pr.proto_name is NULL\nORDER BY bp_name ASC;"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.sen_name\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Top'\n  AND pmodule.proto_name is NULL\nORDER BY material.sen_name ASC"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of hexaboard",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.hxb_name\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Top'\n  AND module.module_name is NULL\nORDER BY material.hxb_name ASC \n"
    }
   ]
  },
  { "title": "LD Bottom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Baseplate",
   "type": "stat",
   "description": "Count of free baseplates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(bp.bp_name)\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Bottom'\n  AND pr.proto_name is NULL"
    }
   ]
  },
  {
   "title": "Sensor",
   "type": "stat",
   "description": "Count of free sensors",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.sen_name)\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Bottom'\n  AND pmodule.proto_name is NULL\n"
    }
   ]
  },
  {
   "title": "hexaboard",
   "type": "stat",
   "description": "Count of free hexaboard\nCheck free entry in **hexaboard** and they are not recorded in **module_assembly** table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.hxb_name)\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Bottom'\n  AND module.module_name is NULL"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT bp.bp_name\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Bottom'\n  AND pr.proto_name is NULL\nORDER BY bp_name ASC;"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.sen_name\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Bottom'\n  AND pmodule.proto_name is NULL\nORDER BY material.sen_name ASC"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of hexaboard",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.hxb_name\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Bottom'\n  AND module.module_name is NULL\nORDER BY material.hxb_name ASC \n"
    }
   ]
  },
  { "title": "LD Left", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Baseplate",
   "type": "stat",
   "description": "Count of free baseplates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(bp.bp_name)\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Left'\n  AND pr.proto_name is NULL"
    }
   ]
  },
  {
   "title": "Sensor",
   "type": "stat",
   "description": "Count of free sensors",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.sen_name)\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Left'\n  AND pmodule.proto_name is NULL\n"
    }
   ]
  },
  {
   "title": "hexaboard",
   "type": "stat",
   "description": "Count of free hexaboard\nCheck free entry in **hexaboard** and they are not recorded in **module_assembly** table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.hxb_name)\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Left'\n  AND module.module_name is NULL"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT bp.bp_name\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Left'\n  AND pr.proto_name is NULL\nORDER BY bp_name ASC;"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.sen_name\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Left'\n  AND pmodule.proto_name is NULL\nORDER BY material.sen_name ASC"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of hexaboard",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.hxb_name\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Left'\n  AND module.module_name is NULL\nORDER BY material.hxb_name ASC \n"
    }
   ]
  },
  { "title": "LD Right", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Baseplate",
   "type": "stat",
   "description": "Count of free baseplates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(bp.bp_name)\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Right'\n  AND pr.proto_name is NULL"
    }
   ]
  },
  {
   "title": "Sensor",
   "type": "stat",
   "description": "Count of free sensors",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.sen_name)\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Right'\n  AND pmodule.proto_name is NULL\n"
    }
   ]
  },
  {
   "title": "hexaboard",
   "type": "stat",
   "description": "Count of free hexaboard\nCheck free entry in **hexaboard** and they are not recorded in **module_assembly** table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.hxb_name)\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Right'\n  AND module.module_name is NULL"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 79 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT bp.bp_name\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Right'\n  AND pr.proto_name is NULL\nORDER BY bp_name ASC;"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 79 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.sen_name\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Right'\n  AND pmodule.proto_name is NULL\nORDER BY material.sen_name ASC"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of hexaboard",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 79 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.hxb_name\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Right'\n  AND module.module_name is NULL\nORDER BY material.hxb_name ASC \n"
    }
   ]
  },
  { "title": "LD Five", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Baseplate",
   "type": "stat",
   "description": "Count of free baseplates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(bp.bp_name)\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Five'\n  AND pr.proto_name is NULL"
    }
   ]
  },
  {
   "title": "Sensor",
   "type": "stat",
   "description": "Count of free sensors",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.sen_name)\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Five'\n  AND pmodule.proto_name is NULL\n"
    }
   ]
  },
  {
   "title": "hexaboard",
   "type": "stat",
   "description": "Count of free hexaboard\nCheck free entry in **hexaboard** and they are not recorded in **module_assembly** table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT COUNT(material.hxb_name)\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Five'\n  AND module.module_name is NULL"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 102 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT bp.bp_name\nFROM public.baseplate bp\nLEFT JOIN public.proto_assembly pr ON bp.bp_name = pr.bp_name\nWHERE bp.proto_no IS NULL \n  AND bp.resolution = 'LD'\n  AND bp.geometry = 'Five'\n  AND pr.proto_name is NULL\nORDER BY bp_name ASC;"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of baseplates",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 102 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.sen_name\nFROM public.sensor material\nLEFT JOIN public.proto_assembly pmodule ON material.sen_name = pmodule.sen_name\nWHERE material.proto_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Five'\n  AND pmodule.proto_name is NULL\nORDER BY material.sen_name ASC"
    }
   ]
  },
  {
   "title": "ID",
   "type": "table",
   "description": "names of hexaboard",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 102 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "SELECT material.hxb_name\nFROM public.hexaboard material\nLEFT JOIN public.module_assembly module ON material.hxb_name = module.hxb_name\nWHERE material.module_no IS NULL \n  AND material.resolution = 'LD'\n  AND material.geometry = 'Five'\n  AND module.module_name is NULL\nORDER BY material.hxb_name ASC \n"
    }
   ]
  }
 ]
}