{
 "title": "IV_Curve Plot for MMTS",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "N_MODULE_SHOW", "label": "Number of Modules to Show", "query": "24" },
   {
    "name": "bp_material",
    "query": "\n            SELECT DISTINCT bp_material::text FROM module_info \n            UNION\n            SELECT 'NULL'\n            ORDER BY bp_material\n            "
   },
   {
    "name": "resolution",
    "query": "\n            SELECT DISTINCT resolution::text FROM module_info \n            UNION\n            SELECT 'NULL'\n            ORDER BY resolution\n            "
   },
   {
    "name": "roc_version",
    "query": "\n            SELECT DISTINCT roc_version::text FROM module_info \n            UNION\n            SELECT 'NULL'\n            ORDER BY roc_version\n            "
   },
   {
    "name": "geometry",
    "query": "\n            SELECT DISTINCT geometry::text FROM module_info \n            UNION\n            SELECT 'NULL'\n            ORDER BY geometry\n            "
   },
   {
    "name": "sen_thickness",
    "query": "\n            SELECT DISTINCT sen_thickness::text FROM module_info \n            UNION\n            SELECT 'NULL'\n            ORDER BY sen_thickness\n            "
   },
   {
    "name": "iv_grade",
    "query": "\n            SELECT DISTINCT iv_grade::text FROM module_qc_summary \n            UNION\n            SELECT 'NULL'\n            ORDER BY iv_grade\n            "
   }
  ]
 },
 "panels": [
  {
   "title": "Ambient-Roomtemp (>20% RH, 10-30°C)",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "\n        WITH latest_qc_summary AS (\n            SELECT DISTINCT ON (module_name) *\n            FROM module_qc_summary\n            ORDER BY module_name, mod_qc_no DESC\n        ), \n\n        latest_iv_test AS (\n            SELECT DISTINCT ON (module_name) *\n            FROM module_iv_test\n            WHERE (module_iv_test.date_test + module_iv_test.time_test)::timestamptz BETWEEN $__timeFrom() AND $__timeTo()\n            AND meas_v IS NOT NULL AND meas_i IS NOT NULL\n            AND (temp_c::float >= 10 AND temp_c::float <= 30)\n            AND (rel_hum::float >= 20)\n            AND temp_c ~ '^[-+]?[0-9]+(\\.[0-9]+)?$'\n            AND rel_hum ~ '^[-+]?[0-9]+(\\.[0-9]+)?$'\n            AND (status_desc = 'Bolted' )\n            AND array_length(meas_v, 1) = array_length(meas_i, 1)\n            ORDER BY module_name, date_test DESC\n        ),\n\n        selected_modules AS (\n        SELECT \n            module_info.module_name\n        FROM module_info\n        JOIN latest_iv_test ON module_info.module_name = latest_iv_test.module_name\n        LEFT JOIN latest_qc_summary ON module_info.module_name = latest_qc_summary.module_name\n        WHERE \n                ('All' = ANY(ARRAY[${bp_material}]) OR \n                (module_info.bp_material IS NULL AND 'NULL' = ANY(ARRAY[${bp_material}])) OR \n                module_info.bp_material::text = ANY(ARRAY[${bp_material}])) AND \n                ('All' = ANY(ARRAY[${resolution}]) OR \n                (module_info.resolution IS NULL AND 'NULL' = ANY(ARRAY[${resolution}])) OR \n                module_info.resolution::text = ANY(ARRAY[${resolution}])) AND \n                ('All' = ANY(ARRAY[${roc_version}]) OR \n                (module_info.roc_version IS NULL AND 'NULL' = ANY(ARRAY[${roc_version}])) OR \n                module_info.roc_version::text = ANY(ARRAY[${roc_version}])) AND \n                ('All' = ANY(ARRAY[${geometry}]) OR \n                (module_info.geometry IS NULL AND 'NULL' = ANY(ARRAY[${geometry}])) OR \n                module_info.geometry::text = ANY(ARRAY[${geometry}])) AND \n                ('All' = ANY(ARRAY[${sen_thickness}]) OR \n                (module_info.sen_thickness IS NULL AND 'NULL' = ANY(ARRAY[${sen_thickness}])) OR \n                module_info.sen_thickness::text = ANY(ARRAY[${sen_thickness}]))\n            AND \n                ('All' = ANY(ARRAY[${iv_grade}]) OR \n                (latest_qc_summary.iv_grade IS NULL AND 'NULL' = ANY(ARRAY[${iv_grade}])) OR \n                latest_qc_summary.iv_grade::text = ANY(ARRAY[${iv_grade}]))\n        ORDER BY module_info.module_no DESC\n        LIMIT ${N_MODULE_SHOW}\n        ),\n\n        filtered_iv AS (\n        SELECT *,\n            meas_i[array_length(meas_i, 1)] AS i_last\n        FROM module_iv_test\n        WHERE\n            module_name IN (SELECT module_name FROM selected_modules)\n        ),\n\n        best_per_module AS (\n        SELECT DISTINCT ON (filtered_iv.module_name) *\n        FROM filtered_iv\n            WHERE (filtered_iv.date_test + filtered_iv.time_test)::timestamptz BETWEEN $__timeFrom() AND $__timeTo()\n            AND (filtered_iv.temp_c::float >= 10 AND filtered_iv.temp_c::float <= 30)\n            AND (filtered_iv.rel_hum::float >= 20)\n            AND (filtered_iv.status_desc = 'Bolted' )\n        ORDER BY filtered_iv.module_name, filtered_iv.mod_ivtest_no DESC\n        ),\n\n        unnested AS (\n        SELECT \n            module_name,\n            ABS(v),\n            i,\n            date_test,\n            time_test\n        FROM best_per_module,\n        UNNEST(meas_v, meas_i) AS t(v, i)\n        )\n\n        SELECT *\n        FROM unnested\n        ORDER BY date_test DESC, time_test DESC;\n        \n"
    }
   ]
  },
  {
   "title": "Dry-Lowtemp (0-12% RH, < -30°C)",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "\n        WITH latest_qc_summary AS (\n            SELECT DISTINCT ON (module_name) *\n            FROM module_qc_summary\n            ORDER BY module_name, mod_qc_no DESC\n        ), \n\n        latest_iv_test AS (\n            SELECT DISTINCT ON (module_name) *\n            FROM module_iv_test\n            WHERE (module_iv_test.date_test + module_iv_test.time_test)::timestamptz BETWEEN $__timeFrom() AND $__timeTo()\n            AND meas_v IS NOT NULL AND meas_i IS NOT NULL\n            AND (temp_c::float < -30)\n            AND (rel_hum::float <= 12)\n            AND temp_c ~ '^[-+]?[0-9]+(\\.[0-9]+)?$'\n            AND rel_hum ~ '^[-+]?[0-9]+(\\.[0-9]+)?$'\n            AND (status_desc = 'Bolted' )\n            AND array_length(meas_v, 1) = array_length(meas_i, 1)\n            ORDER BY module_name, date_test DESC\n        ),\n\n        selected_modules AS (\n        SELECT \n            module_info.module_name\n        FROM module_info\n        JOIN latest_iv_test ON module_info.module_name = latest_iv_test.module_name\n        LEFT JOIN latest_qc_summary ON module_info.module_name = latest_qc_summary.module_name\n        WHERE \n                ('All' = ANY(ARRAY[${bp_material}]) OR \n                (module_info.bp_material IS NULL AND 'NULL' = ANY(ARRAY[${bp_material}])) OR \n                module_info.bp_material::text = ANY(ARRAY[${bp_material}])) AND \n                ('All' = ANY(ARRAY[${resolution}]) OR \n                (module_info.resolution IS NULL AND 'NULL' = ANY(ARRAY[${resolution}])) OR \n                module_info.resolution::text = ANY(ARRAY[${resolution}])) AND \n                ('All' = ANY(ARRAY[${roc_version}]) OR \n                (module_info.roc_version IS NULL AND 'NULL' = ANY(ARRAY[${roc_version}])) OR \n                module_info.roc_version::text = ANY(ARRAY[${roc_version}])) AND \n                ('All' = ANY(ARRAY[${geometry}]) OR \n                (module_info.geometry IS NULL AND 'NULL' = ANY(ARRAY[${geometry}])) OR \n                module_info.geometry::text = ANY(ARRAY[${geometry}])) AND \n                ('All' = ANY(ARRAY[${sen_thickness}]) OR \n                (module_info.sen_thickness IS NULL AND 'NULL' = ANY(ARRAY[${sen_thickness}])) OR \n                module_info.sen_thickness::text = ANY(ARRAY[${sen_thickness}]))\n            AND \n                ('All' = ANY(ARRAY[${iv_grade}]) OR \n                (latest_qc_summary.iv_grade IS NULL AND 'NULL' = ANY(ARRAY[${iv_grade}])) OR \n                latest_qc_summary.iv_grade::text = ANY(ARRAY[${iv_grade}]))\n        ORDER BY module_info.module_no DESC\n        LIMIT ${N_MODULE_SHOW}\n        ),\n\n        filtered_iv AS (\n        SELECT *,\n            meas_i[array_length(meas_i, 1)] AS i_last\n            \n        FROM module_iv_test\n        WHERE\n            module_name IN (SELECT module_name FROM selected_modules)\n        ),\n\n        best_per_module AS (\n        SELECT DISTINCT ON (filtered_iv.module_name) *\n        FROM filtered_iv\n            WHERE (filtered_iv.date_test + filtered_iv.time_test)::timestamptz BETWEEN $__timeFrom() AND $__timeTo()\n            AND filtered_iv.meas_v IS NOT NULL AND filtered_iv.meas_i IS NOT NULL\n            AND (filtered_iv.temp_c::float < -30)\n            AND (filtered_iv.rel_hum::float <= 12)\n            AND (filtered_iv.status_desc = 'Bolted' )\t\t\n        ORDER BY filtered_iv.module_name, filtered_iv.mod_ivtest_no DESC\n        ),\n\n        unnested AS (\n        SELECT \n            module_name,\n            ABS(v),\n            i,\n            date_test,\n            time_test\n        FROM best_per_module,\n        UNNEST(meas_v, meas_i) AS t(v, i)\n        )\n\n        SELECT *\n        FROM unnested\n        ORDER BY date_test DESC, time_test DESC;\n        \n"
    }
   ]
  },
  {
   "title": "Dry-Roomtemp (0-12% RH, 10-30°C)",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "\n        WITH latest_qc_summary AS (\n            SELECT DISTINCT ON (module_name) *\n            FROM module_qc_summary\n            ORDER BY module_name, mod_qc_no DESC\n        ), \n\n        latest_iv_test AS (\n            SELECT DISTINCT ON (module_name) *\n            FROM module_iv_test\n            WHERE (module_iv_test.date_test + module_iv_test.time_test)::timestamptz BETWEEN $__timeFrom() AND $__timeTo()\n            AND meas_v IS NOT NULL AND meas_i IS NOT NULL\n            AND (temp_c::float >= 10 AND temp_c::float <= 30)\n            AND (rel_hum::float <= 12)\n            AND temp_c ~ '^[-+]?[0-9]+(\\.[0-9]+)?$'\n            AND rel_hum ~ '^[-+]?[0-9]+(\\.[0-9]+)?$'\n            AND (status_desc = 'Bolted' )\n            AND array_length(meas_v, 1) = array_length(meas_i, 1)\n            ORDER BY module_name, date_test, time_test DESC\n        ),\n\n        selected_modules AS (\n        SELECT \n            module_info.module_name\n        FROM module_info\n        JOIN latest_iv_test ON module_info.module_name = latest_iv_test.module_name\n        LEFT JOIN latest_qc_summary ON module_info.module_name = latest_qc_summary.module_name\n        WHERE \n                ('All' = ANY(ARRAY[${bp_material}]) OR \n                (module_info.bp_material IS NULL AND 'NULL' = ANY(ARRAY[${bp_material}])) OR \n                module_info.bp_material::text = ANY(ARRAY[${bp_material}])) AND \n                ('All' = ANY(ARRAY[${resolution}]) OR \n                (module_info.resolution IS NULL AND 'NULL' = ANY(ARRAY[${resolution}])) OR \n                module_info.resolution::text = ANY(ARRAY[${resolution}])) AND \n                ('All' = ANY(ARRAY[${roc_version}]) OR \n                (module_info.roc_version IS NULL AND 'NULL' = ANY(ARRAY[${roc_version}])) OR \n                module_info.roc_version::text = ANY(ARRAY[${roc_version}])) AND \n                ('All' = ANY(ARRAY[${geometry}]) OR \n                (module_info.geometry IS NULL AND 'NULL' = ANY(ARRAY[${geometry}])) OR \n                module_info.geometry::text = ANY(ARRAY[${geometry}])) AND \n                ('All' = ANY(ARRAY[${sen_thickness}]) OR \n                (module_info.sen_thickness IS NULL AND 'NULL' = ANY(ARRAY[${sen_thickness}])) OR \n                module_info.sen_thickness::text = ANY(ARRAY[${sen_thickness}]))\n            AND \n                ('All' = ANY(ARRAY[${iv_grade}]) OR \n                (latest_qc_summary.iv_grade IS NULL AND 'NULL' = ANY(ARRAY[${iv_grade}])) OR \n                latest_qc_summary.iv_grade::text = ANY(ARRAY[${iv_grade}]))\n        ORDER BY module_info.module_no DESC\n        LIMIT ${N_MODULE_SHOW}\n        ),\n\n        filtered_iv AS (\n        SELECT *,\n            meas_i[array_length(meas_i, 1)] AS i_last\n        FROM module_iv_test\n        WHERE\n            module_name IN (SELECT module_name FROM selected_modules)\n        ),\n\n        best_per_module AS (\n        SELECT DISTINCT ON (filtered_iv.module_name) *\n        FROM filtered_iv\n\t\t\n            WHERE (filtered_iv.date_test + filtered_iv.time_test)::timestamptz BETWEEN $__timeFrom() AND $__timeTo()\n            AND (filtered_iv.temp_c::float >= 10 AND filtered_iv.temp_c::float <= 30)\n            AND (filtered_iv.rel_hum::float <= 12)\n            AND (filtered_iv.status_desc = 'Bolted' )\n\n        ORDER BY filtered_iv.module_name, filtered_iv.mod_ivtest_no DESC\n        ),\n\n        unnested AS (\n        SELECT \n            module_name,\n            ABS(v),\n            i,\n            date_test,\n            time_test\n        FROM best_per_module,\n        UNNEST(meas_v, meas_i) AS t(v, i)\n        )\n\n        SELECT *\n        FROM unnested\n        ORDER BY date_test DESC, time_test DESC;\n        \n"
    }
   ]
  }
 ]
}