{
 "title": "Thermal Box Environment for MMTS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Average Temperature & Dew Point",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT  \r\n    avg_temp_c AS \"Temperature\", \r\n    bucket_min  AS \"time\" \r\n    FROM avg1m_temperature ORDER BY bucket_min\r\n    DESC \r\n    LIMIT 10\r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT  \r\n    avg_dewpoint_c AS \"Dew Point\", \r\n    bucket_min  AS \"time\" \r\n    FROM avg1m_dewpoint ORDER BY bucket_min\r\n    DESC \r\n    LIMIT 10\r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in the thermal box\n",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"RTD-01\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'RTD-01' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"RTD-02\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'RTD-02' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"RTD-03\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'RTD-03' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"RTD-04\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'RTD-04' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"RTD-05\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'RTD-05' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"RTD-06\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'RTD-06' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"RTD-07\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'RTD-07' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"RTD-08\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'RTD-08' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"Target Temperature\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'Chiller-T' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "timeseries",
   "description": "Dew point in the thermal box",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"DMT-01\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'DMT-01' \r\n    ORDER BY measured_at DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"DMT-02\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'DMT-02' \r\n    ORDER BY measured_at DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    }
   ]
  }
 ]
}