{
 "title": "Thermal Box Environment",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in the thermal box\n",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT \r\n    sensor_id, \r\n    value AS \"Target Temperature\", \r\n    measured_at AS \"time\" \r\n    FROM measurement WHERE sensor_id = 'Chiller-T' \r\n    ORDER BY measured_at \r\n    DESC \r\n    LIMIT 10000 \r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT \r\n    measured_at AS \"time\",\r\n    MAX(CASE WHEN sensor_id = 'RTD-01' THEN value END) AS \"RTD-01\",\r\n    MAX(CASE WHEN sensor_id = 'RTD-02' THEN value END) AS \"RTD-02\",\r\n    MAX(CASE WHEN sensor_id = 'RTD-03' THEN value END) AS \"RTD-03\",\r\n    MAX(CASE WHEN sensor_id = 'RTD-04' THEN value END) AS \"RTD-04\",\r\n    MAX(CASE WHEN sensor_id = 'RTD-05' THEN value END) AS \"RTD-05\",\r\n    MAX(CASE WHEN sensor_id = 'RTD-06' THEN value END) AS \"RTD-06\",\r\n    MAX(CASE WHEN sensor_id = 'RTD-07' THEN value END) AS \"RTD-07\",\r\n    MAX(CASE WHEN sensor_id = 'RTD-08' THEN value END) AS \"RTD-08\"\r\nFROM measurement\r\nWHERE sensor_id IN ('RTD-01', 'RTD-02', 'RTD-03', 'RTD-04', 'RTD-05', 'RTD-06', 'RTD-07', 'RTD-08')\r\n  AND $__timeFilter(measured_at) \r\nGROUP BY measured_at\r\nORDER BY measured_at ASC\r\nLIMIT 10000;"
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "timeseries",
   "description": "Dewpoint in the thermal box",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT \r\n    measured_at AS \"time\",\r\n    MAX(CASE WHEN sensor_id = 'DMT-01' THEN value END) AS \"DMT-01\",\r\n    MAX(CASE WHEN sensor_id = 'DMT-02' THEN value END) AS \"DMT-02\"\r\nFROM measurement\r\nWHERE sensor_id IN ('DMT-01', 'DMT-02')\r\n  AND $__timeFilter(measured_at) \r\nGROUP BY measured_at\r\nORDER BY measured_at ASC\r\nLIMIT 10000;"
    }
   ]
  },
  {
   "title": "Current Average Temperature & Dewpoint",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT  \r\n    avg_temp_c AS \"Temperature\", \r\n    bucket_min  AS \"time\" \r\n    FROM avg1m_temperature ORDER BY bucket_min\r\n    DESC \r\n    LIMIT 10\r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    },
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT * FROM ( \r\n  SELECT  \r\n    avg_dewpoint_c AS \"Dewpoint\", \r\n    bucket_min  AS \"time\" \r\n    FROM avg1m_dewpoint ORDER BY bucket_min\r\n    DESC \r\n    LIMIT 10\r\n  ) \r\nAS sub ORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "SELECT \r\n  measured_at AS \"time\",\r\n  value AS \"status_code\"\r\nFROM measurement\r\nWHERE sensor_id = 'System Status'\r\n  AND $__timeFilter(measured_at)\r\nORDER BY measured_at DESC\r\nLIMIT 1;"
    }
   ]
  }
 ]
}